# Lolibooru 地址
# 若无法访问, 请尝试自行搭建反向代理站点
# 填写该项时, 结尾的 / 可以省略
# 代理站点无法访问时将会尝试访问源站
api-base-url: 'https://lolibooru.moe/'
# 启用本插件的群聊列表
# 除了修改配置外, 你也可以给予权限
enable-groups: []
# 严格模式
# 开启后将过滤掉评级为 q (分级模糊, 可疑) 的图片
strict-mode: true
# 使用 /loli list 命令搜索图片时的最大图片数量
max-search-count: 5
# 使用 /loli list 命令搜索图片超出最大图片数量时的警告
# $at 为 @ 发送者
# $quote 为回复发送者
# $count 为 max-search-count 的值
max-search-count-warn: '$quote图片数量不能超过$count'
# 使用 /loli get 或 loli list 命令获取图片, 下载失败时的代替文字
imageFailDownload: 「图片下载失败」
# 使用 /loli get 或 loli list 命令获取图片, 获取成功的回复信息
replySuccess: "$pic\n图片地址: https://lolibooru.moe/post/show/$id"
# 使用 /loli get 或 loli list 命令获取图片, 获取失败的回复信息
replyFail: '$quote获取失败, 稍后再试吧'
# 使用 /loli get 或 loli list 命令获取图片, 正在获取的回复信息
replyFetching: '$quote正在获取中, 请稍等'
# 使用 /loli get 或 loli list 命令获取图片, 获取完成后撤回正在获取的回复信息
recallFetchingMessage: true
# 使用 /loli get 或 loli list 命令获取图片, 返回图片的画质
quality: SAMPLE
# 使用 /loli get 或 loli list 命令获取图片, 单张图片的连接超时时间 (秒)
timeout: 60
# 使用 /loli get 或 loli list 命令获取图片, 是否顺便保存图片到本地 (data 文件夹)
download: false
# 使用 /loli get 或 loli list 命令获取图片, 重写图片保存路径, 该路径相对于 data/top.mrxiaom.loliyouwant/
overrideDownloadPath: command
# 是否将需要隐藏的 tag 添加到请求地址的参数中
# 开启该选项, 有助于在获取多张图片的情况下让图片数量尽可能多
does-add-tags-to-params: true
# 隐藏 tag 不合适的图片。
# 默认配置的 tag 将会过滤一些 r18 漏网之鱼和部分 r16 图片, 减少可能违规的图片有助于机器人防封。
# 其中 3dcg 为 3D 渲染的图片, 即使是插件作者个人也欣赏不来, 故添加。
# 更新插件并不会更新这个列表, 如有更新该列表的需求, 请到本插件帖子中寻找。
# https://mirai.mamoe.net/topic/1515
hidden-tags: 
  - pantie
  - pantsu
  - underwear
  - navel
  - breast
  - bikini
  - stomach
  - topless
  - bottomless
  - groin
  - butt
  - 3dcg
  - comic
  - bum
  - backside
  - fanny
  - bunny
  - bunny_girl
  - less
  - bottom
  - kiss
  - swimsuit
  - sukusui
  - towel
  - naked_towel
  - denim
  - armpits
  - ribs
  - bare_shoulders
  - translation_request
  - no_bra
  - blush
  - ass
  - absurdres
  - head_out_of_frame
  - spats
  - short
  - short_under_skrit
  - short_skrit
  - thighhighs
# 屏蔽tag数量少于不等于这个数字的图片
# 部分老旧的图片分级不明确, 无法根据tag进行进一步分级
hidden-when-tags-less-than: 26
# 随机发图的关键词, 可自由添加
keywords: 
  来只萝莉: 
    # 指定该关键词包括的 Tag
    tags: []
    # 获取图片的最大数量
    # 接口每次只能申请40张图片, 过滤器会过滤掉一部分, 故该数量仅供限制最多发送数量
    # 若数量大于1, 将通过合并转发发送
    count: 1
    # 单张图片的连接超时时间 (秒)
    timeout: 60
    # 是否需要 @ 机器人来触发随机发图
    at: true
    # 返回图片的画质
    # PREVIEW - 低画质
    # SAMPLE - 中等画质
    # FILE - 原画质
    quality: SAMPLE
    # 获取成功的回复信息
    # $at @发送者
    # $quote 回复发送者
    # $id 图片ID
    # $previewUrl 图片直链 (预览画质)
    # $sampleUrl 图片直链 (中等画质)
    # $fileUrl 图片直链 (原画质)
    # $url 图片直链 (发送的图所选画质)
    # $tags 图片标签
    # $rating 图片分级, q (Questionable) 或者 s (Safe)
    # $pic 下载的图片, 下载失败时用 image-fail-download 的值代替
    replySuccess: "$pic\n图片地址: https://lolibooru.moe/post/show/$id\n标签: $tags"
    # 图片下载失败时的代替文字
    imageFailDownload: 「图片下载失败」
    # 获取失败的回复信息
    # $at @发送者
    # $quote 回复发送者
    replyFail: '$quote获取失败, 稍后再试吧'
    # 正在获取的回复信息
    # $at @发送者
    # $quote 回复发送者
    replyFetching: '$quote正在获取中, 请稍等'
    # 图片获取完成后撤回正在获取的回复信息
    recallFetchingMessage: true
    # 是否顺便保存图片到本地 (data 文件夹)
    download: false
    # 重写图片保存路径, 该路径相对于 data/top.mrxiaom.loliyouwant/
    overrideDownloadPath: ''
    # 执行命令所需金钱的货币类型
    # 留空为不花费金钱
    # 该功能需要安装 mirai-economy-core 插件生效
    costMoneyCurrency: 'mirai-coin'
    # 执行命令所需金钱
    costMoney: 10.0
    # 是否从全局上下文扣除金钱
    # 若关闭该项, 将在用户执行命令所在群的上下文扣除金钱
    # 私聊执行命令将强制使用全局上下文
    costMoneyGlobal: false
    # 执行命令金钱不足提醒
    # $at 为 @ 发送者
    # $quote 为回复发送者
    # $cost 为需要花费的金钱
    costMoneyNotEnough: '$quote你没有足够的 Mirai 币 ($cost) 来执行该命令!'
# 冷却提示
# $at @发送者
# $quote 回复发送者
# $cd 冷却剩余时间
reply-cooldown: '$quote太快了, 再等等吧 ($cd)'
msg-reload: 配置文件已重载
# 冷却时间 (各群独立, 单位是秒)
cooldown: 30
# 获取图片失败时重置的冷却时间 (各群独立, 单位是秒)
fail-cooldown: 3