# 自定义指令触发轮盘赌
# 请注意，该自定义指令的更改必须重启Mirai
alias: 
  - 轮盘
  - 俄罗斯轮盘
# 轮盘等待时间，超过后上一个轮盘失效，单位：秒
waitTime: 600
# 轮盘超时后是否封禁发起人
timeOverBan: false
# 当最后数发均为子弹时强制结束游戏
forceEndWhenAllRamin: true
# 一把枪的弹膛数量是否为随机的
randomChamber: true
# 一把枪有多少个弹膛
# 如果弹膛数量随机为true则此值为随机的最小值
chamber: 6
# 一把枪最大有多少个弹膛
# 如果弹膛数量随机为false则不会有任何作用
chamberMax: 8
# 一把枪上膛的子弹数量是否为随机的
randomBullet: false
# 一把枪有多少发子弹
# 如果子弹数量随机为true则此值为随机的最小值
bullet: 1
# 一把枪最多有多少发子弹
# 如果子弹数量随机为false则不会有任何作用
bulletMax: 2
# 禁言时间是否随机
randomMute: true
# 禁言多少秒(范围1-2592000)
# 如果禁言时间随机为true则此值为随机的最小值
mute: 1
# 禁言最多多少秒(范围1-2592000)
# 如果禁言时间随机为false则不会有任何作用
muteMax: 300
# 起始消息，可用替代项目为:
# <bullet> 子弹数量
# <chamber> 弹膛数量
# <remain-bullet> 剩余子弹数
# <remain-chamber> 剩余击发数
# <mute-s> 禁言时间（单位秒）（例:5）
# <mute-f> 禁言时间（例:11天4时5分14秒）
# <timeout-s> 超时时间（单位秒）（例:5）
# <timeout-f> 超时时间（例:11天4时5分14秒）
# <target> @触发人
messageStart: '新一轮俄罗斯轮盘开启，这是一把<chamber>发的左轮手枪，装填了<bullet>发子弹，击发奖励为禁言<mute-f>，轮盘将于<timeout-f>后超时'
# 结束消息，可用替代项目为:
# <bullet> 子弹数量
# <chamber> 弹膛数量
# <remain-bullet> 剩余子弹数
# <remain-chamber> 剩余击发数
# <mute-s> 禁言时间（单位秒）（例:5）
# <mute-f> 禁言时间（例:11天4时5分14秒）
# <target> @触发人
messageEnd: 此轮俄罗斯轮盘结束
# 超时消息，可用替代项目为:
# <bullet> 子弹数量
# <chamber> 弹膛数量
# <remain-bullet> 剩余子弹数
# <remain-chamber> 剩余击发数
# <mute-s> 禁言时间（单位秒）（例:5）
# <mute-f> 禁言时间（例:11天4时5分14秒）
# <timeout-s> 超时时间（单位秒）（例:5）
# <timeout-f> 超时时间（例:11天4时5分14秒）
# <target> @发起人
messageTimeoutWithBan: '此轮俄罗斯轮盘因超时结束，因未能全部击发发起人<target>被禁言<mute-f>'
# 超时消息，可用替代项目为:
# <bullet> 子弹数量
# <chamber> 弹膛数量
# <remain-bullet> 剩余子弹数
# <remain-chamber> 剩余击发数
# <mute-s> 禁言时间（单位秒）（例:5）
# <mute-f> 禁言时间（例:11天4时5分14秒）
# <timeout-s> 超时时间（单位秒）（例:5）
# <timeout-f> 超时时间（例:11天4时5分14秒）
messageTimeout: 此轮俄罗斯轮盘因超时结束
# 击发消息，可用替代项目为:
# <bullet> 子弹数量
# <chamber> 弹膛数量
# <remain-bullet> 剩余子弹数
# <remain-chamber> 剩余击发数
# <mute-s> 禁言时间（单位秒）（例:5）
# <mute-f> 禁言时间（例:11天4时5分14秒）
# <target> @触发人
messageShot: '<target> 开了一枪，枪响了，被禁言<mute-f>'
# 击发消息但对方是管理员无法禁言，可用替代项目为:
# <bullet> 子弹数量
# <chamber> 弹膛数量
# <remain-bullet> 剩余子弹数
# <remain-chamber> 剩余击发数
# <mute-s> 禁言时间（单位秒）（例:5）
# <mute-f> 禁言时间（例:11天4时5分14秒）
# <target> @触发人
messageShotButAdmin: '<target> 开了一枪，枪响了，但对方是管理员，逃掉了<mute-f>的禁言'
# 未击发消息，可用替代项目为:
# <bullet> 子弹数量
# <chamber> 弹膛数量
# <remain-bullet> 剩余子弹数
# <remain-chamber> 剩余击发数
# <mute-s> 禁言时间（单位秒）（例:5）
# <mute-f> 禁言时间（例:11天4时5分14秒）
# <target> @触发人
messagePass: '<target> 开了一枪，枪没响，还剩<remain-chamber>轮'
# 剩下全是子弹强制结束消息，可用替代项目为:
# <bullet> 子弹数量
# <chamber> 弹膛数量
# <remain-bullet> 剩余子弹数
# <remain-chamber> 剩余击发数
# <mute-s> 禁言时间（单位秒）（例:5）
# <mute-f> 禁言时间（例:11天4时5分14秒）
# <target> @触发人
messageForceEnd: '剩下的发<remain-chamber>全是子弹了，此轮俄罗斯轮盘结束'