# 启用本插件的群聊。填写规则如下
# enable-groups:
# - 群号1
# - 群号2
# - 以此类推
enable-groups: []
# 启用本插件的机器人。如果你只登录了1个机器人，那么不需要去管这个配置。
# 本配置针对登录了多机器人的 mirai 使用，【留空默认为所有机器人可用】。
# 填写规则如下。除了这个配置以外，权限或者 enable-groups 依然是要单独去配置的。
# enable-bots:
# # 允许机器人 12345 在所有群使用该插件
# - '12345:*'
# # 允许机器人 12345 在群 114514 使用该插件
# - '12345:114514'
# # 不允许机器人 12345 在群 114514 使用该插件
# - '12345:-114514'
enable-bots: []
# 抽老婆/换老婆命令冷却时间，单位为秒。两个命令共用一个冷却时间，设置为0或者负数时禁用冷却时间
cooldown: 0
# 是否所有机器人共用一个冷却时间组
cooldown-all-bots: true
# 是否所有群聊共用一个冷却时间组
cooldown-all-groups: true
# 是否所有群员共用一个冷却时间
cooldown-all-members: true
# 冷却中消息，$cooldown 代表剩余秒数
cooldown-message: '$at 正在冷却中 ($cooldown秒)'
# 撤回消息时间，单位为秒，取值在 [1,115] 内有效，超出访问视为禁用该功能
recall-time: 0
# 随机选择时仅包含最近活跃的成员
active-member-only: false
# 群成员活跃状态有效期,单位秒
member-active-time: 604800
# 开启后机器人会响应所有群的命令，在黑名单内的群除外
blacklist-only: false
# 在本插件黑名单内的群聊
blacklist-groups: []
# 「抽老婆」的关键词列表
keywords-random-wife: 
  - 抽老婆
# 「换老婆」的关键词列表
keywords-change-wife: 
  - 换老婆
# 「群老婆列表」的关键词列表
keywords-wife-list-group: 
  - 群老婆列表
# 「老婆列表」的关键词列表
keywords-wife-list-all: 
  - 老婆列表
# 老婆列表图片字体
wife-list-font: 宋体
# 「抽老婆」的回复语句列表
# 其中你的变量有 $at $pic $namecard $nick $qq
# 其中老婆的变量有 $wife_at $wife_pic $wife_namecard $wife_nick $wife_qq
message-random-wife: 
  - "$at 今天你的群友亲爱的是 $wife_pic\n【$wife_namecard】($wife_qq)哒！"
# 「换老婆」的回复语句列表
# 在抽老婆的变量基础上，旧老婆的变量有 $old_wife_at $old_wife_pic $old_wife_namecard $old_wife_nick $old_wife_qq
messages-change-wife: 
  - "$at 今天你的群友亲爱的是 $wife_pic\n【$wife_namecard】($wife_qq)哒！"
# 在抽老婆时是否检查性别 (避免大量请求群员资料导致卡顿，尽量不要开启)
# 开启后只抽性别与用户相反的群友
# 当群友不公开性别时，该选项失效
# 开启本选项会在抽老婆时忽略掉所有不公开性别的群友
check-gender: false
# 同 check-gender，与 check-gender 冲突，两者都开启时，check-gender 失效，该选项生效。
# 开启这个选项后，只能抽到性别与用户相同的群友
check-gender-same: false
# 在抽老婆时是否不允许抽到自己
check-self: true
# 在抽老婆时是否不允许抽到重复的
check-ntr: true
# 插件帮助
message-help: 
  - '变态渣男插件 - 帮助'
  - '  /wuw reload - 重载配置文件'
# 插件重载提示
message-reload: 配置文件已重载