# 图片缓存位置
cache: ImageCache
# 动态 订阅 输出图片数量，负数表示输出全部
limit: 16
# API 访问间隔时间，单位秒
api: 10
# 视频 订阅 访问间隔时间，单位分钟
video: 10
# 动态 订阅 访问间隔时间，单位分钟
dynamic: 10
# 直播 订阅 访问间隔时间，单位分钟
live: 10
# 番剧 订阅 访问间隔时间，单位分钟
season: 30
# 启动时刷新 last
refresh: false
# 排除自动解析
ban: 
  - av1
  - av10492
# 转发自动解析
forward: false
# 自动解析同样内容的间隔
interval: 600000
# 一次性推送的上限
max: 3