# 图片清理间隔，单位小时，默认 1 小时
interval: 
  ARTICLE: 1
  MUSIC: 1
  SKETCH: 1
  DYNAMIC: 1
  VIDEO: 1
  LIVE: 1
  SEASON: 1
  EPISODE: 1
  USER: 1
  EMOJI: 1
# 图片过期时间，单位小时，默认 72 小时
expires: 
  ARTICLE: 72
  MUSIC: 72
  SKETCH: 72
  DYNAMIC: 72
  VIDEO: 72
  LIVE: 72
  SEASON: 72
  EPISODE: 72
  USER: 72
  EMOJI: 72