date_time_pattern: ISO_OFFSET_DATE_TIME
dynamic_forbid_type: []
dynamic_forbid_regexes: []
dynamic_sleep: {}

dynamic_at: {}

video_forbid_type: []
video_forbid_pay: false
video_forbid_union: false
video_forbid_interact: false
video_forbid_playback: false
video_sleep: {}

video_at: {}

season_sleep: {}

season_at: {}

live_sleep: {}

live_at: {}
