# 截图UA
user_agent: 'Mozilla/5.0 (iPad; CPU OS 11_0 like Mac OS X) AppleWebKit/604.1.34 (KHTML, like Gecko) Version/11.0 Mobile/15A5341f Safari/604.1 MicroMessenger'
# 截图宽度
width: 768
# 截图高度
height: 1024
# 无头模式（后台模式）
headless: true
# 隐藏的web组件(jQ选择器)
hide: 
  - '.open-app'
  - '.launch-app-btn'
  - '.unlogin-popover'
  - '.no-login'