# 戳一戳回复的消息
replyMessageList: []
# 事件优先级 从高到低可选 HIGHEST, HIGH, NORMAL, LOW, LOWEST, MONITOR
# 设置后需要重启插件生效
priority: HIGH
# 是否拦截事件 回复后可阻止其它插件响应戳一戳事件 优先级为MONITOR时拦截无效
isIntercept: true
# 群回复间隔（秒），0表示无限制
groupInterval: 0
# 用户私聊回复间隔（秒），0表示无限制
userInterval: 0
interceptAtInterval: true